name: 🚀 Deploy Website via FTP

on:
  push:
    branches:
      - main # or your main branch

jobs:
  ftp-deploy:
    name: Upload to Shared Hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ # directory to upload
