name: 🚀 Deploy Website via FTP

on:
  push:
    branches:
      - main # or your main branch

jobs:
  ftp-deploy:
    name: Upload to Shared Hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Upload via SFTP
        uses: Dylan700/sftp-upload-action@latest
        
        with:
          server: ${{ secrets.SFTP_SERVER }}
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          uploads: |
      ./ => ./www/public_html/
