name: SFTP Deploy with Password

on:
  push:
    branches: [ main ] # Change to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Upload files via SFTP (Password Auth)
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        local_path: './*' # Upload all files from root
        remote_path: '/test'
        # Optional parameters:
        # port: ${{ secrets.SFTP_PORT || '22' }}
        # args: '-r -v' # SFTP arguments
        # debug: 'true'
